config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'welcome/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :user
	validates :name, presence: true
	validates :singer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

   # Para que no realice las acciones del controlador en caso de no estar registrado.
   before_action :authenticate_user!, except: [:index]
	# GET /songs
   def index
   	@songs = Song.all
   end

   # GET /songs/:id
   def show
   	@song = Song.find(params[:id])
   end

   # GET /songs/new
   def new
   	@song = Song.new
   end

   # POST /songs
   def create
      @song = current_user.songs.new(song_params)
      if @song.save
         redirect_to songs_path
      else
         render :new
      end
   end

   # Editar.
   def edit
      @song = Song.find(params[:id])
   end

   def update
      @song = Song.find(params[:id])
      if @song.update(song_params)
         redirect_to songs_path
      else
         render :edit
      end
   end

   # Eliminar
   def destroy
      @song = Song.find(params[:id])
      @song.destroy
      redirect_to songs_path
   end

   # Buscar
   def search
      @song = Song.find_by(params[:name])
   end

   private 
   def song_params
      params.require(:song).permit(:name, :singer, :album, :genre, :state)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def create
		cancion = "%#{params[:keyword]}%"
      if !cancion.nil? then 
         @songs = Song.where("name LIKE ? OR singer LIKE ?", cancion, cancion)
      else
         @songs = Song.all
      end

      respond_to do |format|
         format.html { redirect_to root_path }
         format.js
      end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>MusicHits</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Music Hits</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Canciones", songs_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
            <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Crear cuenta", new_user_registration_path %></li>
            <li><%= link_to "Iniciar sesión", new_user_session_path %></li><% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
</body>

</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
	<% @song.errors.full_messages.each do |message| %>
	<div><%= message %></div>
	<% end %>
	<div class="field">
		<%= f.label :título %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="field">
		<%= f.label :cantante %>
		<%= f.text_field :singer, class: "form-control" %>
	</div>
	<div class="field">
		<%= f.label :Álbum %>
		<%= f.text_field :album, class: "form-control" %>
	</div>
	<div class="field">
		<%= f.label :género %>
		<%= f.text_field :genre, class: "form-control" %>
	</div><br>
	<div class="field">
		<%= f.label :tipo_de_publicación %>
		<%= f.select :state, options_for_select(["Pública","Privada","Compartida"]) %>
	</div><br>
	<div class="field">
		<%= f.submit "Guardar", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/songs/_song.html.erb
<div><strong> <%= song.singer %> </strong></div>

app/views/songs/edit.html.erb
<div style="width: 83%;margin:0 auto;">
<h1>Editar canción</h1><br>
<%= render "form" %>
</div>

app/views/songs/index.html.erb
<div style="width: 84%;margin:0 auto;">
<h1>Canciones</h1><br>
<p>Si no ha iniciado sesión, solo se muestran canciones públicas, para ver más inicie sesión.</p><br>
<div style="width: 50%;margin:500 auto;">
<div class="field">
<%= form_tag "welcome/create", method: :get, remote: true, id:"search-form" do %>
  <%= text_field_tag :keyword, nil, placeholder: "Buscar canción" %>
  <%= content_tag :button, type: :submit, class: "btn btn-primary" do %>
  Buscar
  <% end %>
<% end %>
</div>
</div>
<div class="field">
<div id="resultados">
</div>
</div><br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Título</th>
      <th>Cantante</th>
      <th>Álbum</th>
      <th>Género</th>
      <th>Subida por </th>
    </tr>
  </thead>
  <tbody>
  	 <% @songs.each do |song| %>
  	 <% if song.state == "Pública" %>
    <tr>
      <td><%= song.name %></td>
      <td><%= song.singer %></td>
      <td><%= song.album %></td>
      <td><%= song.genre %></td>
      <% unless song.user.nil? %>
      <td><%= song.user.email %></td>
      <% end %>
      <td><%= link_to "Eliminar", song, method: :delete %></td>
      <td><%= link_to "Editar", edit_song_path(song) %></td>
    </tr>
    <% end %>
    <%if song.state == "Privada" && song.user==current_user%>
    <tr>
      <td><%= song.name %></td>
      <td><%= song.singer %></td>
      <td><%= song.album %></td>
      <td><%= song.genre %></td>
      <% unless song.user.nil? %>
      <td><%= song.user.email %></td>
      <% end %>
      <td><%= link_to "Eliminar", song, method: :delete %></td>
      <td><%= link_to "Editar", edit_song_path(song) %></td>
    </tr>
    <% end %>
    <%if song.state == "Compartida" and !current_user.nil? %>
    <tr>
      <td><%= song.name %></td>
      <td><%= song.singer %></td>
      <td><%= song.album %></td>
      <td><%= song.genre %></td>
      <% unless song.user.nil? %>
      <td><%= song.user.email %></td>
      <% end %>
      <td><%= link_to "Eliminar", song, method: :delete %></td>
      <td><%= link_to "Editar", edit_song_path(song) %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<div><%= link_to "Agregar", controller: "songs", action: "new" %></div>
</div>

app/views/songs/new.html.erb
<div style="width: 83%;margin:0 auto;">
<h1>Agregar canción</h1><br>
<%= render "form" %>
</div>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>
<h1><%= @song.singer %></h1>
<h1><%= @song.album %></h1>

app/views/welcome/index.html.erb
   <div style="width: 85%;margin:0 auto;">
   <% if user_signed_in? %>
   <h1>Bienvenido <%= current_user.email %>
   <% end %>
   </div>
   <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
       <img src="http://diamondcreative.net/plus-v1.1/img/slider/slider_06.jpg" width="1366px" height="700px">
      <div class="carousel-caption hidden-xs">
        <h2>Crea y comparte tu música favorita</h2>
      </div>
    </div>

    <div class="item">
      <img src="http://diamondcreative.net/plus-v1.1/img/slider/slider_03.jpg" width="1366px" height="700px">
      <div class="carousel-caption hidden-xs">
        <h2>Conoce las preferencias de otros usuarios</h2>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>